version: '3.7'

services:
    rugpt3:
        container_name: ruGPT3-server
        build:
            context: .
        volumes:
            - .:/app
        ports:
            - '${HOST_IP}:${HOST_PORT}:${HOST_PORT}'
        command: python src/manage.py runserver ${HOST_IP}:${HOST_PORT}
        env_file:
            - .env
networks:
    back:
volumes:
    rugpt3:
